/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : Time,
  'slug' : IDL.Text,
  'excerpt' : IDL.Text,
});

export const idlService = IDL.Service({
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllPostSlugs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : Time,
    'slug' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  
  return IDL.Service({
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllPostSlugs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };